requires = ["tox>=4.19"]
env_list = ["3.13", "3.12", "3.11", "3.10"]

[env_run_base]
runner = "uv-venv-lock-runner"
description = "Run test under {base_python}"
commands = [["pytest",
             "{posargs:tests}",
             "--cov=.",
             "--cov-append",
             "--cov-report=term",
             "--junitxml=junit.xml",
             "-o",
             "junit_family=legacy"]]
